theme = "nord"

[editor]
line-number = "relative"
bufferline = "multiple"
color-modes = true
auto-pairs = false
shell = ["fish", "-c"]

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
